CREATE DATABASE SISTEMA_FARMACIA
GO

USE SISTEMA_FARMACIA;
GO


CREATE TABLE FORNECEDORES(
CODIGO INT IDENTITY(1,1) NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
CONSTRAINT PK_FORNECEDORES PRIMARY KEY (CODIGO)
)
GO

CREATE TABLE PRODUTOS(
CODIGO_PRODUTO INT IDENTITY(1,1) NOT NULL,
CODIGO INT  NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO NUMERIC(6,2) NOT NULL,
CONSTRAINT PK_PRODUTOS PRIMARY KEY (CODIGO_PRODUTO),
CONSTRAINT FK_FORNECEDORES FOREIGN KEY(CODIGO) REFERENCES FORNECEDORES(CODIGO)
)
GO







